/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Padding = {
  top?: number;
  right?: number;
  bottom?: number;
  left?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Image1 = {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Video = {
  asset?: SanityFileAssetReference;
  media?: unknown;
  _type: "file";
};

export type SectionEyebrow = {
  _type: "sectionEyebrow";
  text: string;
};

export type ImageRow = {
  _type: "imageRow";
  images: Array<
    {
      _key: string;
    } & CaptionedImage
  >;
};

export type CaptionedImage = {
  _type: "captionedImage";
  caption?: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
};

export type Quote = {
  _type: "quote";
  quote: string;
  attribution: string;
};

export type StatRow = {
  _type: "statRow";
  items: Array<{
    kicker?: string;
    value: string;
    label: string;
    _key: string;
  }>;
  note?: string;
};

export type Section = {
  _type: "section";
  eyebrow?: string;
  heading: string;
  tocLabel?: string;
  includeInToc?: boolean;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type MediaGrid = {
  _type: "mediaGrid";
  ratio: "1:1" | "16:9";
  items: Array<
    {
      _key: string;
    } & Media
  >;
  caption?: string;
};

export type MediaBlock = {
  _type: "mediaBlock";
  image: Image1;
  alt: string;
  video?: Video;
  caption?: string;
  fit?: "cover" | "inset";
  stroke?: boolean;
  padding?: Padding;
};

export type Media = {
  _type: "media";
  image: Image1;
  alt: string;
  video?: Video;
  caption?: string;
  fit?: "cover" | "inset";
  stroke?: boolean;
  padding?: Padding;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
  timeline: {
    startMonth:
      | "Jan"
      | "Feb"
      | "Mar"
      | "Apr"
      | "May"
      | "Jun"
      | "Jul"
      | "Aug"
      | "Sep"
      | "Oct"
      | "Nov"
      | "Dec";
    startYear: number;
    endMonth?:
      | "Jan"
      | "Feb"
      | "Mar"
      | "Apr"
      | "May"
      | "Jun"
      | "Jul"
      | "Aug"
      | "Sep"
      | "Oct"
      | "Nov"
      | "Dec";
    endYear?: number;
  };
  role: string;
  collaborators?: Array<{
    name: string;
    title?: string;
    _key: string;
  }>;
  hero: Media;
  accentColor: string;
  year: number;
  category?: string;
  shortDescription?: string;
  previewImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  featured?: boolean;
  orderRank: number;
  body?: Array<
    | ({
        _key: string;
      } & Section)
    | ({
        _key: string;
      } & MediaBlock)
    | ({
        _key: string;
      } & MediaGrid)
    | ({
        _key: string;
      } & StatRow)
    | ({
        _key: string;
      } & Quote)
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | ({
        _key: string;
      } & SectionEyebrow)
    | ({
        _key: string;
      } & CaptionedImage)
    | ({
        _key: string;
      } & ImageRow)
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Padding
  | SanityImageAssetReference
  | Image1
  | SanityFileAssetReference
  | Video
  | SectionEyebrow
  | ImageRow
  | CaptionedImage
  | Quote
  | StatRow
  | Section
  | MediaGrid
  | MediaBlock
  | Media
  | CaseStudy
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/sanity/caseStudyQueries.ts
// Variable: CASE_STUDIES_INDEX_QUERY
// Query: *[_type == "caseStudy"] | order(orderRank asc) {    _id,    title,    "slug": slug.current,    accentColor,    year,    category,    shortDescription,    previewImage,    "heroStill": hero.image,    "preview": hero.video.asset->url,    featured,    orderRank  }
export type CASE_STUDIES_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  accentColor: string;
  year: number;
  category: string | null;
  shortDescription: string | null;
  previewImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  heroStill: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  preview: string | null;
  featured: boolean | null;
  orderRank: number;
}>;

// Source: lib/sanity/caseStudyQueries.ts
// Variable: CASE_STUDY_BY_SLUG_QUERY
// Query: *[_type == "caseStudy" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    description,    timeline,    role,    collaborators[]{ name, title },    hero{  alt,  caption,  fit,  stroke,  padding{ top, right, bottom, left },  image,  "width": image.asset->metadata.dimensions.width,  "height": image.asset->metadata.dimensions.height,  video{ asset->{ url } }},    accentColor,    year,    category,    shortDescription,    previewImage,    featured,    orderRank,    body[]{      ...,      _type == "section" => {        ...,        body[]      },      _type == "mediaBlock" => {        ...,          alt,  caption,  fit,  stroke,  padding{ top, right, bottom, left },  image,  "width": image.asset->metadata.dimensions.width,  "height": image.asset->metadata.dimensions.height,  video{ asset->{ url } }      },      _type == "mediaGrid" => {        ...,        items[]{          ...,            alt,  caption,  fit,  stroke,  padding{ top, right, bottom, left },  image,  "width": image.asset->metadata.dimensions.width,  "height": image.asset->metadata.dimensions.height,  video{ asset->{ url } }        }      }    }  }
export type CASE_STUDY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  description: string;
  timeline: {
    startMonth:
      | "Apr"
      | "Aug"
      | "Dec"
      | "Feb"
      | "Jan"
      | "Jul"
      | "Jun"
      | "Mar"
      | "May"
      | "Nov"
      | "Oct"
      | "Sep";
    startYear: number;
    endMonth?:
      | "Apr"
      | "Aug"
      | "Dec"
      | "Feb"
      | "Jan"
      | "Jul"
      | "Jun"
      | "Mar"
      | "May"
      | "Nov"
      | "Oct"
      | "Sep";
    endYear?: number;
  };
  role: string;
  collaborators: Array<{
    name: string;
    title: string | null;
  }> | null;
  hero: {
    alt: string;
    caption: string | null;
    fit: "cover" | "inset" | null;
    stroke: boolean | null;
    padding: {
      top: number | null;
      right: number | null;
      bottom: number | null;
      left: number | null;
    } | null;
    image: Image1;
    width: number | null;
    height: number | null;
    video: {
      asset: {
        url: string;
      } | null;
    } | null;
  };
  accentColor: string;
  year: number;
  category: string | null;
  shortDescription: string | null;
  previewImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  featured: boolean | null;
  orderRank: number;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "captionedImage";
        caption?: string;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        alt: string;
      }
    | {
        _key: string;
        _type: "imageRow";
        images: Array<
          {
            _key: string;
          } & CaptionedImage
        >;
      }
    | {
        _key: string;
        _type: "mediaBlock";
        image: Image1;
        alt: string;
        video: {
          asset: {
            url: string;
          } | null;
        } | null;
        caption: string | null;
        fit: "cover" | "inset" | null;
        stroke: boolean | null;
        padding: {
          top: number | null;
          right: number | null;
          bottom: number | null;
          left: number | null;
        } | null;
        width: number | null;
        height: number | null;
      }
    | {
        _key: string;
        _type: "mediaGrid";
        ratio: "1:1" | "16:9";
        items: Array<{
          _key: string;
          _type: "media";
          image: Image1;
          alt: string;
          video: {
            asset: {
              url: string;
            } | null;
          } | null;
          caption: string | null;
          fit: "cover" | "inset" | null;
          stroke: boolean | null;
          padding: {
            top: number | null;
            right: number | null;
            bottom: number | null;
            left: number | null;
          } | null;
          width: number | null;
          height: number | null;
        }>;
        caption?: string;
      }
    | {
        _key: string;
        _type: "quote";
        quote: string;
        attribution: string;
      }
    | {
        _key: string;
        _type: "section";
        eyebrow?: string;
        heading: string;
        tocLabel?: string;
        includeInToc?: boolean;
        body: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: never;
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }> | null;
      }
    | {
        _key: string;
        _type: "sectionEyebrow";
        text: string;
      }
    | {
        _key: string;
        _type: "contrast";
        before: {
          heading: string;
          label: string;
        } | null;
        after: {
          heading: string;
          label: string;
        } | null;
      }
    | {
        _key: string;
        _type: "statRow";
        items: Array<{
          kicker?: string;
          value: string;
          label: string;
          _key: string;
        }>;
        note?: string;
      }
  > | null;
} | null;

// Source: lib/sanity/queries.ts
// Variable: projectCardsQuery
// Query: *[_type == "project"] | order(order asc) {    "slug": slug.current,    title,    cardTitle,    year,    summary,    gated,    order,    selected,    indexTitle,    discipline,    color,    href,    preview,    thumbnail  }
export type ProjectCardsQueryResult = Array<never>;

// Source: lib/sanity/queries.ts
// Variable: projectHeroQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    "slug": slug.current,    title,    summary,    impact,    timeline,    role,    collaborators[]{ name, role },    gated,    thumbnail  }
export type ProjectHeroQueryResult = null;

// Source: lib/sanity/queries.ts
// Variable: projectBodyQuery
// Query: *[_type == "project" && slug.current == $slug][0] {    body[]{      ...,      _type == "figure" => {        ...,        image      },      _type == "figureGrid" => {        ...,        figures[]{ ..., image }      },      _type == "videoBlock" => {        ...,        poster      }    }  }
export type ProjectBodyQueryResult = null;

// Source: lib/sanity/queries.ts
// Variable: publicProjectSlugsQuery
// Query: *[_type == "project" && gated != true].slug.current
export type PublicProjectSlugsQueryResult = Array<never>;
